### ISSUE TITLE
Imbalance of GPU comsumption.

### ISSUE THREAD

**Issue by Zzmonica** [MILVLG/mcan-vqa#14]
Hi! I have ran into a problem that when I running the model, the GPU-0 always takes large memory,while other GPUs take less memory, any suggestion?
Hope for your respond.

**Comment by yuzcccc** [comment]
please provide a more detailed description:
1. Are you training with multi-gpu training? 
2. What is the memory costs of GPU-0 and the rest?
3. Does the memory gap cause other problems like training speed bottleneck or out-of-memory?

**Comment by Zzmonica** [comment]
More details:

- I'm training with 4 GPUs.

- During training, (by the way, I'm training with`train+val+vg` SPLIT and with `large` mode. BATCH_SIZE = 400.)  GPU-0 always costs ~3000MB more than other 3 GPUs, and I have tried some methods like DistributedDataParallel, DistributedSampler, but it seems not improve the situation.

- The memory gap limits the training batch size so maybe it can be one reason to influence the training speed I think. 

- During evaluation, GPU memory cost is balance.

Thanks for your respond and hope for your suggestion!

**Comment by yuzcccc** [comment]
The Multi-GPU implementations indeed consume more GPU usage on GPU-0 (about 20%), and in our current implementation, **multi-thread-based** strategy is used and  the speed-up ratio is not satisfactory : ( 

Therefore, we only use it when a model is too large to be trained in one GPU rather than for acceleration (we have tried 2 GPUs at most). If you really want to obtain acceleration, maybe you should modify the code and take some **multi-process-based** strategies.

Finally, in our experiments, a too-large batch size may hurt MCAN's performance. Therefore, we only use 64 for all the experiments. If you have other results, please let us know.
