### ISSUE TITLE
Why use only image guided-attention rather than both image and question guided-attention? 

### ISSUE THREAD

**Issue by ghost** [MILVLG/mcan-vqa#35]
Thanks for making your great work open-source!
Curious about why use only image guided-attention rather than both image and question guided-attention.
Frankly, both directions of attention are important. 
Have you ever done some experiments about that?
Looking forward to your reply.

**Comment by MIL-VLG** [comment]
We have tested this variant, as mentioned in our paper (section 3.2):

MCA variants like the symmetric architectures GA(X,Y)-GA(Y,X) and SGA(X,Y)-SGA(Y,X). However, these MCA variants do not report comparative performance, so we do not discuss them further due to space limitations.

Since this is quite easy to reimplement, you can try it yourself, and if you obtain different observations, please let us know.
