### ISSUE TITLE
Feature file download failed

### ISSUE THREAD

**Issue by AIstudentSH** [MILVLG/mcan-vqa#4]
During the feature file download process, the speed is normal at the beginning but the connection is disconnected during the process. And it can't be reconnected.Could you please provide a download address suitable for Chinese users? For example, the download address of Baidu Netdisk.In addition, since I have not used it before, installing spacy in anaconda has also caused some problems.
特征文件下载过程中，开始时速度正常但是过程中会断开连接。而且无法重连。能否请您提供一个适合中国用户使用的下载地址？比如百度网盘的下载地址。另外，由于我之前没有使用过，在anaconda中安装spacy也出了些问题。

**Comment by MIL-VLG** [comment]
Please checkout our latest updates. See the README for details

1. For bottom-up-attention features, we have also provided the files on BaiduYun. 

2. For spacy, we simplify the way to install the spacy package and remove the cmd of `python -m download en` to avoid the problem caused by poor networking
